### PR TITLE
Ceramic selfID: Update ID format

### PR DESCRIPTION
**Pull request by GorniyGor**
1) 3ID authentication method pattern looks like `did:3:...` without `id` word 
2) Since Ceramic updates a default authentication method from 3ID DIDs -> PKH DIDs, the id looks like `did:pkh:...`

### CODE REVIEW

**Comment by ljcutts** [comment]
Hello @GorniyGor, can you change it to `did:pkh`. Once you do this, I will merge your PR.

**Comment by ljcutts** [comment]
Hello @GorniyGor, Can you do `did:pkh:...` ? Once you do this, I will merge your PR.

**Comment by GorniyGor** [comment]
@ljcutts done

**Comment by ljcutts** [comment]
Thank you @GorniyGor

**Pull request merged**
